import type { FixFindingOutcome } from "../fix/schema.js";
import type { FinalFinding } from "../findings/schema.js";
import type { ParsedPr } from "../github/parsePrUrl.js";
import type { ArtifactPaths } from "../storage/artifactPaths.js";
import type { CommandExecution, VerificationResults } from "../workspace/schema.js";
import { dirname, relative } from "node:path";
import { fence, link, plural, sanitizeInline } from "./markdownHelpers.js";

/**
 * Phase 11 — fix report generation. Like `renderMarkdownReport` this is a PURE,
 * IO-free renderer over the fix run's in-memory results, returning the
 * `.ai-review/fix_report.md` string. Its job (PRD Phase 11 acceptance): explain
 * what was changed, what was not and why, how verification went, and what
 * still needs a human.
 */

export interface FixReportInput {
  pr: ParsedPr;
  /** All findings in `final_findings.json`. */
  totalFinalFindings: number;
  /** Findings matching the fixable filter (before the cap). */
  fixableCount: number;
  /** The `fix.maxFindings` cap in effect. */
  maxFindings: number;
  /** The selected findings, for suggested-fix fallbacks on failures. */
  selected: FinalFinding[];
  outcomes: FixFindingOutcome[];
  patchWritten: boolean;
  /** True when `--apply` left the workspace checkout patched. */
  workspaceLeftPatched: boolean;
  /** Post-fix verification results, or null when the run aborted before that stage. */
  verification: VerificationResults | null;
  /** True when the PR head moved since the review run (findings may be stale). */
  headMoved: boolean;
  meta: { toolVersion: string; generatedAt: string };
  /** Artifact layout — used to compute relative links from `fix_report.md`. */
  paths: ArtifactPaths;
}

export function renderFixReport(input: FixReportInput): string {
  const fixed = input.outcomes.filter((o) => o.status === "fixed");
  const notFixed = input.outcomes.filter((o) => o.status !== "fixed");

  const out: string[] = ["# AI Fix Report", ""];
  out.push(...renderSummary(input, fixed.length, notFixed));
  out.push(...renderFixed(fixed));
  out.push(...renderNotFixed(notFixed, input.selected));
  out.push(...renderVerificationSection(input.verification, input.paths));
  out.push(...renderHowToApply(input));
  out.push(...renderRawArtifacts(input.paths, input.patchWritten, input.verification !== null));
  out.push("---", "");
  out.push(`_Generated by pr-war-room v${input.meta.toolVersion} at ${input.meta.generatedAt}._`);
  out.push("");
  return out.join("\n");
}

/* -------------------------------- summary -------------------------------- */

function renderSummary(
  input: FixReportInput,
  fixedCount: number,
  notFixed: FixFindingOutcome[],
): string[] {
  const { pr } = input;
  const failed = notFixed.filter((o) => o.status === "failed").length;
  const skipped = notFixed.filter((o) => o.status === "skipped").length;

  const capNote =
    input.fixableCount > input.outcomes.length
      ? ` (capped at \`fix.maxFindings=${input.maxFindings}\`)`
      : "";

  const out: string[] = ["## Summary", ""];
  out.push(
    `- **PR:** [${pr.owner}/${pr.repo}#${pr.number}](https://github.com/${pr.owner}/${pr.repo}/pull/${pr.number})`,
  );
  out.push(
    `- **Findings:** ${input.outcomes.length} of ${input.fixableCount} fixable ${plural(input.fixableCount, "finding")} attempted${capNote} — ${input.totalFinalFindings} total in the final report`,
  );
  out.push(`- **Outcome:** ${fixedCount} fixed, ${failed} failed, ${skipped} skipped`);
  out.push(
    `- **Patch:** ${input.patchWritten ? `written to ${link(input.paths.fix.report, input.paths.fix.patch)}` : "none produced"}`,
  );
  out.push(`- **Verification:** ${verificationSummary(input.verification)}`);
  out.push(
    `- **Workspace:** ${
      input.workspaceLeftPatched
        ? "left PATCHED (`--apply`) at `.ai-review/workspace/repo` — your own working tree was not touched"
        : "reverted to the PR head (patch preserved in `patch.diff`)"
    }`,
  );
  if (input.headMoved) {
    out.push(
      "- **Warning:** the PR head moved since the review run — the findings (and these fixes) may be stale. Consider re-running `pr-war-room review`.",
    );
  }
  out.push("");
  return out;
}

function verificationSummary(v: VerificationResults | null): string {
  if (v === null || !v.ran) {
    // Em-dash, not parens: the skip reason itself contains a parenthesized hint.
    const reason = v?.skipReason ? ` — ${v.skipReason}` : "";
    return `not run${reason}`;
  }
  return v.allPassed ? "all commands passed ✓" : "failures present ✗";
}

/* -------------------------------- findings ------------------------------- */

function renderFixed(fixed: FixFindingOutcome[]): string[] {
  const out: string[] = ["## Fixed", ""];
  if (fixed.length === 0) {
    out.push("_None._", "");
    return out;
  }
  for (const o of fixed) {
    out.push(`### ${sanitizeInline(o.title)}`, "");
    out.push(`- **Classification:** ${o.classification}`);
    out.push(`- **File:** ${o.file === null ? "(none)" : `\`${o.file}\``}`);
    out.push(`- **Edits applied:** ${o.edits_applied}`);
    if (o.summary !== null && o.summary.trim() !== "") {
      out.push("", `**What changed:** ${sanitizeInline(o.summary)}`);
    }
    if (o.needs_manual_review !== null && o.needs_manual_review.trim() !== "") {
      out.push("", `> **Needs manual review:** ${sanitizeInline(o.needs_manual_review)}`);
    }
    out.push("");
  }
  return out;
}

function renderNotFixed(notFixed: FixFindingOutcome[], selected: FinalFinding[]): string[] {
  const findingById = new Map(selected.map((f) => [f.cluster_id, f]));
  const out: string[] = ["## Not Fixed", ""];
  if (notFixed.length === 0) {
    out.push("_None._", "");
    return out;
  }
  out.push("These findings still need a human:", "");
  for (const o of notFixed) {
    out.push(`### ${sanitizeInline(o.title)}`, "");
    out.push(`- **Classification:** ${o.classification}`);
    out.push(`- **File:** ${o.file === null ? "(none)" : `\`${o.file}\``}`);
    if (o.failure !== null) {
      out.push(`- **Why:** \`${o.failure.kind}\` — ${sanitizeInline(o.failure.message)}`);
    }
    if (o.needs_manual_review !== null && o.needs_manual_review.trim() !== "") {
      out.push("", `> **Needs manual review:** ${sanitizeInline(o.needs_manual_review)}`);
    }
    const suggested = findingById.get(o.cluster_id)?.suggested_fix;
    if (suggested !== null && suggested !== undefined && suggested.trim() !== "") {
      out.push(
        "",
        "<details><summary>Reviewer-suggested fix</summary>",
        "",
        fence(suggested.trim()),
        "",
        "</details>",
      );
    }
    out.push("");
  }
  return out;
}

/* ------------------------------ verification ------------------------------ */

function renderVerificationSection(
  v: VerificationResults | null,
  paths: ArtifactPaths,
): string[] {
  const out: string[] = ["## Verification", ""];
  if (v === null || !v.ran) {
    const reason = v?.skipReason ?? "not run";
    out.push(
      `_Verification skipped — ${reason}. Pass \`--verify\` to run it against the patched code._`,
      "",
    );
    return out;
  }
  out.push(`- **Result:** ${v.allPassed ? "all passed ✓" : "failures present ✗"}`);
  if (v.install) out.push(...renderCommand(v.install, "Install"));
  for (const cmd of v.results) out.push(...renderCommand(cmd));
  for (const skippedCmd of v.skippedCommands) {
    out.push(`- \`${skippedCmd}\`: skipped${v.skipReason ? ` (${v.skipReason})` : ""}`);
  }
  out.push("");
  out.push(`_Full output: ${link(paths.fix.report, paths.fix.verification)}_`, "");
  return out;
}

function renderCommand(c: CommandExecution, label = ""): string[] {
  const prefix = label ? `${label} ` : "";
  const status = c.passed ? "✓" : c.timedOut ? "timed out ✗" : "✗";
  const lines = [`- ${prefix}\`${c.command}\`: exit ${c.exitCode ?? "—"} ${status}`];
  if (!c.passed) {
    const output = (c.stderrPreview || c.stdoutPreview || c.spawnError || "").trim();
    if (output) lines.push("", "<details><summary>output</summary>", "", fence(output), "", "</details>");
  }
  return lines;
}

/* ------------------------------ how to apply ------------------------------ */

function renderHowToApply(input: FixReportInput): string[] {
  const out: string[] = ["## How to Apply", ""];
  if (!input.patchWritten) {
    out.push("_No patch was produced, so there is nothing to apply._", "");
    return out;
  }
  // The patch lives in the run-scoped directory; render the path relative to
  // the `.ai-review` root's parent (the repository/base dir the user runs from).
  const patchPath = relative(dirname(input.paths.root), input.paths.fix.patch);
  out.push(
    "From your repository root (same repo and branch as the PR head):",
    "",
    "```sh",
    `git apply --check ${patchPath}   # preview first`,
    `git apply ${patchPath}`,
    "```",
    "",
    `If your tree has drifted from the PR head, \`git apply --3way ${patchPath}\``,
    "can merge the changes instead.",
    "",
  );
  if (input.workspaceLeftPatched) {
    out.push(
      "The workspace checkout at `.ai-review/workspace/repo` already contains these",
      "fixes (`--apply`). The tool never touches your own working tree, never",
      "commits, and never pushes.",
      "",
    );
  }
  return out;
}

/* -------------------------------- artifacts ------------------------------- */

function renderRawArtifacts(
  paths: ArtifactPaths,
  patchWritten: boolean,
  verificationWritten: boolean,
): string[] {
  const out: string[] = ["## Raw Artifacts", ""];
  const targets = [
    // Only link artifacts this run actually wrote — a dead link reads as a bug.
    ...(patchWritten ? [paths.fix.patch] : []),
    paths.fix.results,
    ...(verificationWritten ? [paths.fix.verification] : []),
    paths.fix.metadata,
    paths.finalFindings,
  ];
  for (const t of targets) out.push(`- ${link(paths.fix.report, t)}`);
  out.push("");
  return out;
}
