import { dirname, relative } from "node:path";
import type {
  PacketVerification,
  PacketVerificationCommand,
} from "../context/types.js";
import type { JudgeClassification, SupportLevel } from "../findings/schema.js";
import { esc, fileHref, safeHttpHref } from "./htmlHelpers.js";
import { plural } from "./markdownHelpers.js";
import {
  buildFunnel,
  buildPool,
  collectDropped,
  readinessVerdict,
  summarizeGate,
  type GateSummary,
  type ReportFinding,
  type ReportInput,
} from "./reportModel.js";

/**
 * Phase 10 — the PRIMARY user-facing report: a single self-contained HTML file
 * (`report.html`). Pure renderer (no IO), same `ReportInput` and the same
 * `reportModel.ts` derivations as the Markdown report, so the two renderings
 * can never disagree about the pool, the verdict, or what was dropped.
 *
 * Properties the file guarantees:
 *  - SELF-CONTAINED & OFFLINE: embedded CSS and a small vanilla script; no CDN,
 *    fonts, images, or network requests of any kind. The only external href is
 *    the PR's own GitHub URL (validated http(s), escaped).
 *  - SAFE AGAINST INJECTION: every untrusted string (titles, claims, evidence,
 *    file names, PR metadata, stdout/stderr) passes through `esc()`; the script
 *    block is a static string with no interpolated data and never assigns
 *    `innerHTML`.
 *  - READABLE AT SCALE: findings are cards grouped by classification, evidence
 *    shows the strongest items first with the tail collapsed, and a filter bar
 *    (severity / category / file / skeptic support / text search) works
 *    client-side on data attributes.
 *  - HONEST: skeptic/judge fallbacks (e.g. timeouts) are marked on the summary
 *    AND on each affected card — a finding kept unvalidated is never presented
 *    as validated.
 */

/** Evidence items visible before the collapsible "show more" tail. */
export const HTML_INLINE_EVIDENCE = 3;

export function renderHtmlReport(input: ReportInput): string {
  const pool = buildPool(input);
  const dropped = collectDropped(input);

  const blockers = pool.filter((f) => f.classification === "blocker");
  const shouldFix = pool.filter((f) => f.classification === "should_fix_before_review");
  const optional = pool.filter((f) => f.classification === "nice_to_have");

  const p = input.packet.pr;
  const verdict = readinessVerdict(blockers.length, shouldFix.length, input.packet.verification);
  const verdictTone =
    blockers.length > 0 ? "blocker" : shouldFix.length > 0 ? "should" : "ready";

  const skepticSummary = input.options.skepticEnabled
    ? summarizeGate(input.skepticResults)
    : null;
  const judgeSummary =
    input.options.judgeEnabled && input.ranked !== null ? summarizeGate(input.ranked) : null;

  const prHref = safeHttpHref(p.htmlUrl);
  const prLabel = esc(`${p.owner}/${p.repo}#${p.number}`);

  const body = `
<header class="topbar">
  <div class="wrap topbar-row">
    <span class="wordmark">PR&nbsp;WAR&nbsp;ROOM</span>
    <span class="topbar-meta">
      ${prHref === null ? prLabel : `<a href="${prHref}">${prLabel}</a>`}
      <span class="sep">·</span> run ${esc(input.meta.runId)}
      <span class="sep">·</span> ${esc(input.meta.generatedAt)}
    </span>
  </div>
</header>

<main class="wrap">
  <section class="hero verdict-${verdictTone}" aria-label="Review verdict">
    <p class="eyebrow">AI pre-review verdict</p>
    <h1>${esc(p.title)}</h1>
    <p class="verdict">${esc(verdict)}</p>
    ${renderFunnel(input, dropped.length)}
    ${renderTiles(blockers.length, shouldFix.length, optional.length, dropped.length)}
    ${renderGateNotes(skepticSummary, judgeSummary)}
  </section>

  ${renderFilterBar(pool)}

  <p id="no-matches" class="empty" hidden>No findings match the current filters.</p>

  ${renderSection("blockers", "Must fix before human review", "Merge-blocking problems the reviewers verified in the changed code.", blockers)}
  ${renderSection("should-fix", "Should fix before human review", "Likely human-review comments — address them to save a round-trip.", shouldFix)}
  ${renderSection("optional", "Nice to have", "Lower-stakes improvements; fix opportunistically.", optional)}

  ${renderVerification(input.packet.verification)}
  ${renderDropped(dropped)}
  ${renderArtifacts(input)}
</main>

<footer class="wrap footer">
  Generated by pr-war-room v${esc(input.meta.toolVersion)} · run ${esc(input.meta.runId)} · ${esc(input.meta.generatedAt)} · works offline, no external assets
</footer>`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light dark">
<title>${esc(`AI Pre-Review — ${p.owner}/${p.repo}#${p.number}`)}</title>
<style>${CSS}</style>
</head>
<body>
${body}
<script>${SCRIPT}</script>
</body>
</html>
`;
}

/* ------------------------------ hero pieces ------------------------------ */

function renderFunnel(input: ReportInput, droppedTotal: number): string {
  const cells = buildFunnel(input)
    .map(
      (s, i) => `
    <div class="funnel-stage" data-stage="${i}">
      <span class="funnel-value">${s.value}</span>
      <span class="funnel-label">${esc(s.label)}</span>
      <span class="funnel-hint">${esc(s.hint)}</span>
    </div>`,
    )
    .join('<div class="funnel-arrow" aria-hidden="true">→</div>');
  return `
  <div class="funnel" role="group" aria-label="Finding funnel">
    ${cells}
    <div class="funnel-dropped">${droppedTotal} dropped along the way</div>
  </div>`;
}

function renderTiles(blockers: number, shouldFix: number, optional: number, dropped: number): string {
  const tile = (cls: string, label: string, value: number): string => `
    <div class="tile tile-${cls}">
      <span class="tile-value">${value}</span>
      <span class="tile-label">${esc(label)}</span>
    </div>`;
  return `
  <div class="tiles" role="group" aria-label="Findings by priority">
    ${tile("blocker", "Blockers", blockers)}
    ${tile("should", "Should fix", shouldFix)}
    ${tile("optional", "Nice to have", optional)}
    ${tile("dropped", "Dropped", dropped)}
  </div>`;
}

function renderGateNotes(skeptic: GateSummary | null, judge: GateSummary | null): string {
  const lines: string[] = [];
  const describe = (name: string, s: GateSummary, verb: string): string => {
    const parts: string[] = [];
    if (s.llm > 0) parts.push(`${s.llm} ${verb} by LLM`);
    if (s.deterministic > 0) parts.push(`${s.deterministic} deterministic`);
    if (s.fallback > 0) {
      parts.push(
        `<strong class="warn-text">⚠ ${s.fallback} kept by recall-first fallback${s.timeouts > 0 ? ` (${s.timeouts} timed out)` : ""}</strong>`,
      );
    }
    return `<span class="gate"><span class="gate-name">${esc(name)}</span> ${parts.join(" · ") || "no clusters to assess"}</span>`;
  };
  if (skeptic !== null) lines.push(describe("Skeptic", skeptic, "validated"));
  if (judge !== null) lines.push(describe("Judge", judge, "ranked"));
  if (lines.length === 0) return "";
  return `<div class="gates">${lines.join("")}</div>`;
}

/* ------------------------------- filter bar ------------------------------ */

function renderFilterBar(pool: ReportFinding[]): string {
  const options = (values: string[]): string =>
    [...new Set(values)]
      .sort((a, b) => a.localeCompare(b))
      .map((v) => `<option value="${esc(v)}">${esc(v)}</option>`)
      .join("");

  const severities = options(pool.map((f) => f.cluster.severity));
  const categories = options(pool.map((f) => f.cluster.category));
  const files = options(pool.map((f) => f.cluster.file ?? "(no file)"));
  const supports = options(pool.map((f) => supportKey(f)));

  return `
  <section class="filters" aria-label="Filter findings">
    <input id="f-search" type="search" placeholder="Search title, claim, evidence…" aria-label="Search findings">
    <select id="f-severity" aria-label="Filter by severity"><option value="">severity: all</option>${severities}</select>
    <select id="f-category" aria-label="Filter by category"><option value="">category: all</option>${categories}</select>
    <select id="f-file" aria-label="Filter by file"><option value="">file: all</option>${files}</select>
    <select id="f-support" aria-label="Filter by skeptic support"><option value="">skeptic: all</option>${supports}</select>
    <span id="f-count" class="filter-count" role="status"></span>
  </section>`;
}

/** The skeptic facet value a card is filterable by. */
function supportKey(f: ReportFinding): string {
  if (f.skeptic === null) return "not run";
  if (f.skeptic.failure !== null) return "fallback (unvalidated)";
  if (f.support !== null) return `support: ${f.support}`;
  return "deterministic";
}

/* ------------------------------- sections -------------------------------- */

function renderSection(
  id: string,
  heading: string,
  subtitle: string,
  findings: ReportFinding[],
): string {
  const cards =
    findings.length === 0
      ? `<p class="empty">None.</p>`
      : findings.map(renderCard).join("\n");
  return `
  <section class="findings-section" id="section-${esc(id)}" data-section>
    <h2>${esc(heading)} <span class="count" data-count>${findings.length}</span></h2>
    <p class="section-sub">${esc(subtitle)}</p>
    ${cards}
  </section>`;
}

const CLASSIFICATION_LABEL: Record<Exclude<JudgeClassification, "drop">, string> = {
  blocker: "Blocker",
  should_fix_before_review: "Should fix",
  nice_to_have: "Nice to have",
};

const SUPPORT_LABEL: Record<SupportLevel, string> = {
  strong: "strong support",
  medium: "medium support",
  weak: "weak support",
  unsupported: "unsupported",
};

function renderCard(f: ReportFinding): string {
  const c = f.cluster;
  const fileLabel = c.file === null ? "(no file)" : c.file;
  const lines =
    c.line_start === 0 && c.line_end === 0 ? "" : `:${c.line_start}–${c.line_end}`;

  const badges: string[] = [
    `<span class="badge badge-${f.classification === "blocker" ? "blocker" : f.classification === "should_fix_before_review" ? "should" : "optional"}">${CLASSIFICATION_LABEL[f.classification]}</span>`,
    // Skip the severity badge when it would literally repeat the
    // classification badge ("Blocker blocker").
    ...(c.severity === "blocker" && f.classification === "blocker"
      ? []
      : [`<span class="badge badge-severity">${esc(c.severity)}</span>`]),
    `<span class="badge badge-category">${esc(c.category)}</span>`,
  ];

  return `
  <article class="card" data-card
    data-severity="${esc(c.severity)}"
    data-category="${esc(c.category)}"
    data-file="${esc(fileLabel)}"
    data-support="${esc(supportKey(f))}">
    <div class="card-head">
      <div class="badges">${badges.join(" ")}</div>
      <h3>${esc(c.merged_title)}</h3>
      <p class="card-meta">
        <code class="loc">${esc(fileLabel)}${esc(lines)}</code>
        <span class="sep">·</span> ${c.agreement} ${plural(c.agreement, "reviewer")}, ${c.source_finding_ids.length} ${plural(c.source_finding_ids.length, "finding")} merged
        <span class="sep">·</span> score ${f.score.toFixed(2)}
        <span class="sep">·</span> confidence ${c.confidence.toFixed(2)}
      </p>
    </div>

    <p class="claim"><strong>Why this matters.</strong> ${esc(c.claim)}</p>

    ${renderVerdicts(f)}
    ${renderSuggestion("Suggested fix", c.suggested_fix)}
    ${renderSuggestion("Suggested test", c.suggested_test)}
    ${renderEvidence(c.evidence)}
    ${renderProvenance(f)}
  </article>`;
}

/** Skeptic + judge verdict strip; a fallback-kept finding is flagged loudly. */
function renderVerdicts(f: ReportFinding): string {
  const rows: string[] = [];

  if (f.skeptic !== null) {
    if (f.skeptic.failure !== null) {
      const what = f.skeptic.failure.kind === "timeout" ? "Skeptic timed out" : `Skeptic failed (${f.skeptic.failure.kind})`;
      rows.push(
        `<p class="verdict-row verdict-warn">⚠ <strong>${esc(what)}</strong> — finding kept by recall-first fallback; it was <em>not</em> adversarially validated.</p>`,
      );
    } else if (f.support !== null) {
      rows.push(
        `<p class="verdict-row"><span class="verdict-tag verdict-${esc(f.support)}">skeptic: ${esc(SUPPORT_LABEL[f.support])}</span> ${esc(f.skeptic.decision.reason)}</p>`,
      );
    } else {
      rows.push(
        `<p class="verdict-row"><span class="verdict-tag verdict-det">skeptic: deterministic</span> ${esc(f.skeptic.decision.reason)}</p>`,
      );
    }
  }

  if (f.judge !== null) {
    if (f.judge.failure !== null) {
      rows.push(
        `<p class="verdict-row verdict-warn">⚠ <strong>Judge ${f.judge.failure.kind === "timeout" ? "timed out" : `failed (${esc(f.judge.failure.kind)})`}</strong> — classified deterministically (recall-first fallback).</p>`,
      );
    } else {
      const src = f.judge.source === "llm" ? "judge" : "judge (deterministic)";
      rows.push(
        `<p class="verdict-row"><span class="verdict-tag verdict-judge">${esc(src)}: ${esc(f.judge.decision.classification)}</span> ${esc(f.judge.decision.reason)}</p>`,
      );
    }
  }

  return rows.length > 0 ? `<div class="verdicts">${rows.join("")}</div>` : "";
}

function renderSuggestion(label: string, value: string | null): string {
  if (value === null || value.trim() === "") return "";
  const v = value.trim();
  if (v.includes("\n") || v.length > 220) {
    return `
    <details class="suggestion">
      <summary>${esc(label)}</summary>
      <pre>${esc(v)}</pre>
    </details>`;
  }
  return `<p class="suggestion-inline"><strong>${esc(label)}.</strong> ${esc(v)}</p>`;
}

/** Strongest evidence first (mergeCluster ordering); the tail collapses. */
function renderEvidence(evidence: string[]): string {
  const inline = evidence.slice(0, HTML_INLINE_EVIDENCE);
  const rest = evidence.slice(HTML_INLINE_EVIDENCE);
  const items = (xs: string[]): string => xs.map((e) => `<li>${esc(e)}</li>`).join("");
  const more =
    rest.length === 0
      ? ""
      : `
      <details class="evidence-more">
        <summary>Show ${rest.length} more evidence ${plural(rest.length, "item")}</summary>
        <ul class="evidence">${items(rest)}</ul>
      </details>`;
  return `
    <div class="evidence-block">
      <p class="evidence-title">Evidence <span class="count">${evidence.length}</span></p>
      <ul class="evidence">${items(inline)}</ul>
      ${more}
    </div>`;
}

/** Source agents — the provenance strip at the card's foot. */
function renderProvenance(f: ReportFinding): string {
  const agents = f.cluster.source_agents.map((a) => `<code>${esc(a)}</code>`).join(" ");
  return `<p class="provenance">Reported by ${agents}</p>`;
}

/* ----------------------------- verification ------------------------------ */

function renderVerification(v: PacketVerification): string {
  let body: string;
  if (!v.ran) {
    body = `<p class="empty">Verification not run (detection only). Re-run with <code>--verify</code> to execute install + test/lint/build.</p>`;
  } else {
    const rows: string[] = [];
    if (v.install) rows.push(renderVerificationRow(v.install, "install"));
    for (const cmd of v.commands) rows.push(renderVerificationRow(cmd));
    body = `
    <p class="verification-result ${v.allPassed ? "ok-text" : "warn-text"}">${v.allPassed ? "✓ All commands passed" : "✗ Failures present"}</p>
    <div class="verification-rows">${rows.join("")}</div>`;
  }
  return `
  <section class="findings-section" id="section-verification">
    <h2>Verification</h2>
    ${body}
  </section>`;
}

function renderVerificationRow(c: PacketVerificationCommand, label = ""): string {
  const status = c.passed ? `<span class="ok-text">✓ passed</span>` : c.timedOut ? `<span class="warn-text">✗ timed out</span>` : `<span class="warn-text">✗ failed</span>`;
  const output = (c.stderrPreview || c.stdoutPreview || c.spawnError || "").trim();
  const detail =
    !c.passed && output
      ? `
      <details class="cmd-output">
        <summary>output</summary>
        <pre>${esc(output)}</pre>
      </details>`
      : "";
  return `
  <div class="verification-row">
    <code class="cmd">${label ? `<span class="cmd-label">${esc(label)}</span> ` : ""}${esc(c.command)}</code>
    <span class="cmd-status">${status} <span class="muted">exit ${c.exitCode ?? "—"}</span></span>
    ${detail}
  </div>`;
}

/* ------------------------------- dropped --------------------------------- */

function renderDropped(dropped: ReturnType<typeof collectDropped>): string {
  const body =
    dropped.length === 0
      ? `<p class="empty">Nothing was dropped.</p>`
      : `
    <details class="dropped-details">
      <summary>Show ${dropped.length} dropped ${plural(dropped.length, "finding")} and why</summary>
      <ul class="dropped-list">
        ${dropped
          .map(
            (d) =>
              `<li><strong>${esc(d.title)}</strong> <span class="badge badge-dropped">${esc(d.stage)}</span><br><span class="muted">${esc(d.reason)}</span></li>`,
          )
          .join("")}
      </ul>
    </details>`;
  return `
  <section class="findings-section" id="section-dropped">
    <h2>Dropped findings <span class="count">${dropped.length}</span></h2>
    <p class="section-sub">Excluded by the skeptic or the judge — kept here so the tool can always explain what it dropped and why.</p>
    ${body}
  </section>`;
}

/* ------------------------------- artifacts ------------------------------- */

function renderArtifacts(input: ReportInput): string {
  const { paths, options } = input;
  const from = dirname(paths.reportHtml);
  const targets: string[] = [
    paths.runMetadata,
    paths.context.packetJson,
    paths.normalized.allFindings,
    paths.deduped.clusters,
    paths.deduped.stats,
  ];
  if (options.skepticEnabled) targets.push(paths.skeptic.results);
  if (options.judgeEnabled) targets.push(paths.judge.ranked, paths.finalFindings);
  targets.push(paths.reportMd);
  const items = targets
    .map((t) => {
      const rel = relative(from, t);
      return `<li><a href="${fileHref(rel)}"><code>${esc(rel)}</code></a></li>`;
    })
    .join("");
  return `
  <section class="findings-section" id="section-artifacts">
    <h2>Raw artifacts</h2>
    <p class="section-sub">The machine-readable trail behind this report — full evidence, per-agent raw output, and every gate's verdict.</p>
    <ul class="artifact-list">${items}</ul>
  </section>`;
}

/* --------------------------------- CSS ----------------------------------- */

/**
 * Embedded stylesheet. Design notes: the report leads with the tool's terminal
 * DNA — a dark command bar with a monospace wordmark, mono eyebrows/labels —
 * over a calm paper surface; the only saturated color is the severity story
 * (status reds/ambers/blues), so a wall of blockers *looks* like a wall of
 * blockers. Dark mode derives from the same roles via prefers-color-scheme.
 */
const CSS = `
:root {
  --page: #f6f6f3;
  --card: #fcfcfb;
  --ink: #171613;
  --ink-2: #52514e;
  --muted: #898781;
  --hairline: #e3e2da;
  --bar: #16150f;
  --bar-ink: #f3f2ec;
  --ok: #006300;
  --warn: #8a4a12;
  --blocker: #b02a2a;
  --blocker-bg: #fbeaea;
  --should-bg: #fdf1e7;
  --should: #8a4a12;
  --optional: #1c5cab;
  --optional-bg: #eaf2fc;
  --dropped-bg: #f0efec;
  --focus: #1c5cab;
  --mono: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  --sans: system-ui, -apple-system, "Segoe UI", sans-serif;
}
@media (prefers-color-scheme: dark) {
  :root {
    --page: #131311;
    --card: #1c1c19;
    --ink: #f2f1ea;
    --ink-2: #c3c2b7;
    --muted: #8f8d85;
    --hairline: #32312c;
    --bar: #0b0b09;
    --bar-ink: #f3f2ec;
    --ok: #4cc38a;
    --warn: #e8a35c;
    --blocker: #e66767;
    --blocker-bg: #3a1d1d;
    --should-bg: #38281a;
    --should: #e8a35c;
    --optional: #7db3ee;
    --optional-bg: #1a2940;
    --dropped-bg: #262622;
    --focus: #7db3ee;
  }
}

* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--page);
  color: var(--ink);
  font: 15px/1.55 var(--sans);
}
.wrap { max-width: 880px; margin: 0 auto; padding: 0 20px; }
a { color: var(--optional); }
code { font-family: var(--mono); font-size: 0.86em; }
:focus-visible { outline: 2px solid var(--focus); outline-offset: 2px; }

/* command bar */
.topbar { background: var(--bar); color: var(--bar-ink); }
.topbar-row { display: flex; align-items: baseline; justify-content: space-between; gap: 12px; padding: 12px 20px; flex-wrap: wrap; }
.wordmark { font-family: var(--mono); font-weight: 700; letter-spacing: 0.22em; font-size: 13px; }
.topbar-meta { font-family: var(--mono); font-size: 12px; opacity: 0.75; }
.topbar-meta a { color: inherit; }
.sep { opacity: 0.5; margin: 0 2px; }

/* hero */
.hero { padding: 28px 0 8px; border-bottom: 1px solid var(--hairline); }
.eyebrow { font-family: var(--mono); text-transform: uppercase; letter-spacing: 0.18em; font-size: 11px; color: var(--muted); margin: 0 0 6px; }
.hero h1 { font-size: 26px; line-height: 1.25; margin: 0 0 10px; letter-spacing: -0.01em; }
.verdict { font-size: 17px; margin: 0 0 20px; padding-left: 12px; border-left: 4px solid var(--muted); }
.verdict-blocker .verdict { border-color: var(--blocker); }
.verdict-should .verdict { border-color: var(--should); }
.verdict-ready .verdict { border-color: var(--ok); }

/* funnel — the signature strip: how 5 stages of filtering earn the report */
.funnel { display: flex; align-items: stretch; gap: 8px; flex-wrap: wrap; padding: 14px; border: 1px solid var(--hairline); border-radius: 10px; background: var(--card); }
.funnel-stage { display: flex; flex-direction: column; min-width: 86px; padding: 2px 6px; }
.funnel-value { font-size: 24px; font-weight: 650; }
.funnel-label { font-family: var(--mono); font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: var(--ink-2); }
.funnel-hint { font-size: 11px; color: var(--muted); }
.funnel-arrow { align-self: center; color: var(--muted); }
.funnel-dropped { margin-left: auto; align-self: center; font-family: var(--mono); font-size: 11px; color: var(--muted); }

/* stat tiles */
.tiles { display: grid; grid-template-columns: repeat(auto-fit, minmax(130px, 1fr)); gap: 10px; margin: 14px 0 6px; }
.tile { background: var(--card); border: 1px solid var(--hairline); border-left-width: 4px; border-radius: 8px; padding: 10px 12px; display: flex; flex-direction: column; }
.tile-value { font-size: 26px; font-weight: 650; }
.tile-label { font-family: var(--mono); font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: var(--ink-2); }
.tile-blocker { border-left-color: var(--blocker); }
.tile-should { border-left-color: var(--should); }
.tile-optional { border-left-color: var(--optional); }
.tile-dropped { border-left-color: var(--muted); }

.gates { display: flex; flex-direction: column; gap: 2px; margin: 10px 0 18px; font-size: 13px; color: var(--ink-2); }
.gate-name { font-family: var(--mono); text-transform: uppercase; letter-spacing: 0.08em; font-size: 11px; color: var(--muted); margin-right: 6px; }
.warn-text { color: var(--warn); }
.ok-text { color: var(--ok); }

/* filters */
.filters { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; padding: 16px 0 4px; position: sticky; top: 0; background: var(--page); z-index: 2; }
.filters input[type="search"] { flex: 1 1 220px; }
.filters input, .filters select {
  font: 13px var(--mono); color: var(--ink);
  background: var(--card); border: 1px solid var(--hairline); border-radius: 7px; padding: 7px 9px;
}
.filter-count { font-family: var(--mono); font-size: 12px; color: var(--muted); margin-left: auto; }

/* sections + cards */
.findings-section { padding: 22px 0 6px; }
.findings-section h2 { font-size: 18px; margin: 0 0 2px; letter-spacing: -0.01em; }
.section-sub { margin: 0 0 14px; color: var(--muted); font-size: 13px; }
.count { font-family: var(--mono); font-size: 12px; color: var(--muted); font-weight: 400; }
.empty { color: var(--muted); font-size: 14px; }

.card { background: var(--card); border: 1px solid var(--hairline); border-radius: 10px; padding: 16px 18px 12px; margin: 0 0 12px; }
.badges { display: flex; gap: 6px; flex-wrap: wrap; margin-bottom: 8px; }
.badge { font-family: var(--mono); font-size: 11px; letter-spacing: 0.04em; padding: 2px 8px; border-radius: 999px; border: 1px solid transparent; }
.badge-blocker { background: var(--blocker-bg); color: var(--blocker); border-color: var(--blocker); }
.badge-should { background: var(--should-bg); color: var(--should); border-color: var(--should); }
.badge-optional { background: var(--optional-bg); color: var(--optional); border-color: var(--optional); }
.badge-severity, .badge-category { background: transparent; color: var(--ink-2); border-color: var(--hairline); }
.badge-dropped { background: var(--dropped-bg); color: var(--ink-2); }
.card h3 { font-size: 16px; margin: 0 0 6px; line-height: 1.35; }
.card-meta { font-size: 12.5px; color: var(--muted); margin: 0 0 10px; }
.loc { background: var(--dropped-bg); padding: 1px 6px; border-radius: 5px; }
.claim { margin: 0 0 10px; }

.verdicts { border-top: 1px dashed var(--hairline); padding-top: 8px; margin-bottom: 8px; }
.verdict-row { font-size: 13px; color: var(--ink-2); margin: 0 0 6px; }
.verdict-row.verdict-warn { color: var(--warn); }
.verdict-tag { font-family: var(--mono); font-size: 11px; padding: 1px 7px; border-radius: 999px; border: 1px solid var(--hairline); margin-right: 6px; white-space: nowrap; }
.verdict-strong { color: var(--ok); border-color: var(--ok); }
.verdict-medium { color: var(--optional); border-color: var(--optional); }
.verdict-weak, .verdict-unsupported { color: var(--warn); border-color: var(--warn); }

.suggestion-inline { margin: 0 0 8px; font-size: 14px; }
.suggestion summary, .evidence-more summary, .cmd-output summary, .dropped-details summary { cursor: pointer; font-size: 13px; color: var(--optional); font-family: var(--mono); }
.suggestion pre, .cmd-output pre { background: var(--dropped-bg); border-radius: 8px; padding: 10px 12px; overflow-x: auto; font-family: var(--mono); font-size: 12.5px; line-height: 1.5; white-space: pre-wrap; word-break: break-word; }

.evidence-block { margin: 4px 0 8px; }
.evidence-title { font-family: var(--mono); font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: var(--muted); margin: 0 0 4px; }
.evidence { margin: 0; padding-left: 20px; font-size: 13.5px; color: var(--ink-2); }
.evidence li { margin-bottom: 4px; }
.evidence-more { margin-top: 4px; }
.evidence-more ul { margin-top: 6px; }

.provenance { border-top: 1px dashed var(--hairline); margin: 8px 0 0; padding-top: 8px; font-size: 12px; color: var(--muted); }
.provenance code { background: var(--dropped-bg); padding: 1px 5px; border-radius: 4px; margin-right: 2px; }

/* verification */
.verification-result { font-weight: 600; }
.verification-row { padding: 8px 0; border-bottom: 1px solid var(--hairline); font-size: 13.5px; }
.verification-row .cmd { display: inline-block; margin-right: 10px; }
.cmd-label { color: var(--muted); text-transform: uppercase; font-size: 10px; letter-spacing: 0.08em; margin-right: 4px; }
.cmd-status { white-space: nowrap; }
.muted { color: var(--muted); }

.dropped-list { padding-left: 20px; font-size: 13.5px; }
.dropped-list li { margin-bottom: 8px; }
.artifact-list { padding-left: 20px; font-size: 13.5px; }
.artifact-list li { margin-bottom: 3px; }

.footer { padding: 26px 20px 40px; color: var(--muted); font-family: var(--mono); font-size: 11.5px; }

@media (prefers-reduced-motion: no-preference) {
  .card { transition: border-color 120ms ease; }
  .card:hover { border-color: var(--muted); }
}
@media print {
  .filters { display: none; }
  .topbar { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
}
`;

/* -------------------------------- script --------------------------------- */

/**
 * Client-side filtering. STATIC — no report data is interpolated in, so
 * untrusted content can never reach a script context; it only reads the
 * (escaped) data attributes and text content the renderer produced.
 */
const SCRIPT = `
(function () {
  "use strict";
  var search = document.getElementById("f-search");
  var selects = ["f-severity", "f-category", "f-file", "f-support"].map(function (id) {
    return document.getElementById(id);
  });
  var facets = ["severity", "category", "file", "support"];
  var cards = Array.prototype.slice.call(document.querySelectorAll("[data-card]"));
  var sections = Array.prototype.slice.call(document.querySelectorAll("[data-section]"));
  var countEl = document.getElementById("f-count");
  var noMatches = document.getElementById("no-matches");
  if (!search || !countEl) return;

  function apply() {
    var q = search.value.trim().toLowerCase();
    var active = selects.map(function (s) { return s ? s.value : ""; });
    var shown = 0;
    cards.forEach(function (card) {
      var ok = true;
      for (var i = 0; i < facets.length; i++) {
        if (active[i] && card.getAttribute("data-" + facets[i]) !== active[i]) { ok = false; break; }
      }
      if (ok && q) ok = card.textContent.toLowerCase().indexOf(q) !== -1;
      card.hidden = !ok;
      if (ok) shown++;
    });
    sections.forEach(function (section) {
      var sectionCards = section.querySelectorAll("[data-card]");
      var visible = 0;
      sectionCards.forEach(function (c) { if (!c.hidden) visible++; });
      section.hidden = sectionCards.length > 0 && visible === 0;
      var count = section.querySelector("[data-count]");
      if (count) count.textContent = String(visible);
    });
    var filtering = q !== "" || active.some(function (v) { return v !== ""; });
    countEl.textContent = filtering ? "showing " + shown + " of " + cards.length : cards.length + " findings";
    if (noMatches) noMatches.hidden = !(filtering && shown === 0);
  }

  search.addEventListener("input", apply);
  selects.forEach(function (s) { if (s) s.addEventListener("change", apply); });
  apply();
})();
`;
