import type {
  PacketVerification,
  PacketVerificationCommand,
} from "../context/types.js";
import type { FindingCluster } from "../findings/schema.js";
import type { ArtifactPaths } from "../storage/artifactPaths.js";
import { fence, link, plural, sanitizeInline } from "./markdownHelpers.js";
import {
  buildFunnel,
  buildPool,
  collectDropped,
  readinessVerdict,
  summarizeGate,
  verificationSummary,
  type DroppedEntry,
  type GateSummary,
  type ReportFinding,
  type ReportInput,
} from "./reportModel.js";

/**
 * Phase 10 — Markdown report generation (PRD §10.9). A PURE, IO-free renderer:
 * it takes the pipeline's already-computed, already-validated in-memory objects
 * and returns the `report.md` string. Keeping it pure (no disk reads, no writes)
 * mirrors `renderReviewPacketMarkdown` and makes every branch — the grouping,
 * the caps, the degraded modes — unit-testable without a filesystem.
 *
 * Since the HTML report became the primary user-facing artifact, this renderer
 * is the secondary/legacy rendering; both consume the same `reportModel.ts`
 * derivations so they can never disagree.
 *
 * The report is deliberately concise (§9.2 actionable-over-exhaustive): grouped
 * findings with their evidence, a verification summary, a dropped-count, and
 * links to the raw JSON artifacts — never raw model output.
 */

export type { ReportInput } from "./reportModel.js";

/**
 * Evidence items shown inline per finding; the rest collapse into a
 * `<details>` block. Keeps a big merged cluster's section readable (the demo's
 * worst case was an 84-item wall) while every item stays one click away — and
 * all of them remain in the JSON artifacts.
 */
export const MAX_INLINE_EVIDENCE = 5;

const HEADER = "# AI Pre-Review Report";

export function renderMarkdownReport(input: ReportInput): string {
  const pool = buildPool(input);

  // Summary buckets reflect the TRUE totals (pre-cap); the sections below show
  // only what fits the display budget, with the difference called out.
  const poolBlockers = pool.filter((f) => f.classification === "blocker").length;
  const poolShouldFix = pool.filter((f) => f.classification === "should_fix_before_review").length;
  const optionalCount = pool.filter((f) => f.classification === "nice_to_have").length;

  // includeNiceToHave FIRST so hidden optionals never consume the maxFindings cap.
  const filtered = input.options.includeNiceToHave
    ? pool
    : pool.filter((f) => f.classification !== "nice_to_have");
  const hiddenOptional = input.options.includeNiceToHave ? 0 : optionalCount;

  const displayed = filtered.slice(0, Math.max(0, input.options.maxFindings));
  const omittedByCap = filtered.length - displayed.length;

  const mustFix = displayed.filter((f) => f.classification === "blocker");
  const shouldFix = displayed.filter((f) => f.classification === "should_fix_before_review");
  const optional = displayed.filter((f) => f.classification === "nice_to_have");

  // How many of each class the `maxFindings` cap pushed off the end. The verdict
  // and the Summary counts stay on the TRUE (pre-cap) totals; these per-class
  // omission counts let every section and the omission note say honestly what
  // was hidden — never call a capped blocker "lower-priority", and never print
  // "_None._" for a class that only looks empty because it was capped.
  const capped = filtered.slice(displayed.length);
  const omittedBlockers = capped.filter((f) => f.classification === "blocker").length;
  const omittedShouldFix = capped.filter(
    (f) => f.classification === "should_fix_before_review",
  ).length;
  const omittedOptional = capped.filter((f) => f.classification === "nice_to_have").length;

  const dropped = collectDropped(input);

  const out: string[] = [];
  out.push(HEADER, "");
  out.push(
    ...renderSummary(input, {
      poolBlockers,
      poolShouldFix,
      optionalCount,
      hiddenOptional,
      omittedByCap,
      omittedBlockers,
      omittedShouldFix,
      displayedEmpty: displayed.length === 0,
      poolEmpty: pool.length === 0,
      droppedTotal: dropped.length,
    }),
  );
  out.push(...renderFindingSection("Must Fix Before Human Review", mustFix, omittedBlockers));
  out.push(...renderFindingSection("Should Fix Before Human Review", shouldFix, omittedShouldFix));
  out.push(...renderSuggestedTests(displayed));
  out.push(
    ...renderOptionalSection(
      optional,
      input.options.includeNiceToHave,
      hiddenOptional,
      omittedOptional,
    ),
  );
  out.push(...renderVerificationSection(input.packet.verification, input.paths));
  out.push(...renderDropped(dropped));
  out.push(...renderRawArtifacts(input));

  out.push("---", "");
  out.push(
    `_Generated by pr-war-room v${input.meta.toolVersion} at ${input.meta.generatedAt} (run ${input.meta.runId})._`,
  );
  out.push("");

  return out.join("\n");
}

/* -------------------------------- summary -------------------------------- */

interface SummaryCounts {
  poolBlockers: number;
  poolShouldFix: number;
  optionalCount: number;
  hiddenOptional: number;
  omittedByCap: number;
  /** High-priority findings the cap hid — surfaced explicitly, not as "lower-priority". */
  omittedBlockers: number;
  omittedShouldFix: number;
  displayedEmpty: boolean;
  /** No finding survived skeptic+judge (distinct from "all survivors are hidden optionals"). */
  poolEmpty: boolean;
  droppedTotal: number;
}

function renderSummary(input: ReportInput, c: SummaryCounts): string[] {
  const p = input.packet.pr;
  const title = sanitizeInline(p.title);
  const out: string[] = ["## Summary", ""];

  out.push(`- **PR:** [${p.owner}/${p.repo}#${p.number} — ${title}](${p.htmlUrl})`);
  out.push(`- **Result:** ${readinessVerdict(c.poolBlockers, c.poolShouldFix, input.packet.verification)}`);

  const notes: string[] = [];
  if (c.hiddenOptional > 0) {
    notes.push(
      `${c.hiddenOptional} optional ${plural(c.hiddenOptional, "finding")} hidden — enable \`review.includeNiceToHave\` to show`,
    );
  }
  if (c.omittedByCap > 0) {
    // Name the high-priority items the cap hid rather than calling everything
    // beyond the limit "lower-priority" — a capped blocker is still a blocker.
    const highPriority: string[] = [];
    if (c.omittedBlockers > 0) {
      highPriority.push(`${c.omittedBlockers} ${plural(c.omittedBlockers, "blocker")}`);
    }
    if (c.omittedShouldFix > 0) highPriority.push(`${c.omittedShouldFix} should-fix`);
    // Em-dash (not parens) so this reads cleanly inside the Findings line's own
    // parenthesized note suffix rather than nesting `(… (…))`.
    const detail = highPriority.length > 0 ? ` — including ${highPriority.join(", ")}` : "";
    notes.push(
      `${c.omittedByCap} ${plural(c.omittedByCap, "finding")} beyond the \`maxFindings=${input.options.maxFindings}\` limit not shown${detail}`,
    );
  }
  const noteSuffix = notes.length > 0 ? ` (${notes.join("; ")})` : "";
  out.push(
    `- **Findings:** ${c.poolBlockers} blocker, ${c.poolShouldFix} should-fix, ${c.optionalCount} optional${noteSuffix}`,
  );

  out.push(`- **Verification:** ${verificationSummary(input.packet.verification)}`);
  out.push(`- **Funnel:** ${renderFunnel(input, c.droppedTotal)}`);
  out.push(...renderGateLines(input));

  if (c.displayedEmpty) {
    // Distinguish the three ways the body can be empty by the FUNNEL, not the
    // raw count: nothing found, everything dropped (nothing survived), or
    // survivors exist but are all hidden optionals (the default
    // includeNiceToHave=false path). The old raw-count branch wrongly claimed
    // "all dropped" for the last case, contradicting "Dropped Findings: None".
    let note: string;
    if (input.rawFindingCount === 0) {
      note = "The reviewers surfaced no findings on this PR.";
    } else if (c.poolEmpty) {
      note = "All findings were dropped as unsupported or low-value — see Dropped Findings.";
    } else {
      note =
        "All surviving findings are optional and hidden — enable `review.includeNiceToHave` to show them.";
    }
    out.push(`- **Note:** ${note}`);
  }

  out.push("");
  return out;
}

/**
 * One summary line per precision gate saying how it actually decided — and,
 * crucially, whether any finding was kept by a fallback (e.g. a timeout)
 * without validation. The first demo run hit skeptic timeouts that were only
 * visible in the JSON artifacts; the report must say so up front.
 */
function renderGateLines(input: ReportInput): string[] {
  const out: string[] = [];
  if (input.options.skepticEnabled) {
    out.push(`- **Skeptic:** ${gateLine(summarizeGate(input.skepticResults), "validated by LLM")}`);
  }
  if (input.options.judgeEnabled && input.ranked !== null) {
    out.push(`- **Judge:** ${gateLine(summarizeGate(input.ranked), "ranked by LLM")}`);
  }
  return out;
}

function gateLine(s: GateSummary, llmVerb: string): string {
  const parts: string[] = [];
  if (s.llm > 0) parts.push(`${s.llm} ${llmVerb}`);
  if (s.deterministic > 0) parts.push(`${s.deterministic} deterministic`);
  if (s.fallback > 0) {
    const timeoutNote =
      s.timeouts > 0 ? ` (${s.timeouts} timed out — kept by recall-first fallback, unvalidated)` : " (kept by recall-first fallback)";
    parts.push(`⚠ ${s.fallback} fallback${timeoutNote}`);
  }
  return parts.length > 0 ? parts.join(", ") : "no clusters to assess";
}

/** Prose rendering of the shared funnel stages (reportModel owns the stage set). */
function renderFunnel(input: ReportInput, droppedTotal: number): string {
  const parts = buildFunnel(input).map((s) => {
    switch (s.key) {
      case "raw":
        return `${s.value} raw ${plural(s.value, "finding")}`;
      case "clusters":
        return `${s.value} ${plural(s.value, "cluster")}`;
      case "skeptic":
        return `${s.value} after skeptic`;
      case "judge":
        return `${s.value} ranked`;
    }
  });
  return `${parts.join(" → ")} (${droppedTotal} dropped)`;
}

/* ------------------------------- findings -------------------------------- */

function renderFindingSection(
  heading: string,
  findings: ReportFinding[],
  omittedInClass = 0,
): string[] {
  const out: string[] = [`## ${heading}`, ""];
  // Only truly empty (nothing here AND nothing capped) prints "_None._".
  // A class the cap emptied says so, so it never contradicts the Summary count.
  if (findings.length === 0 && omittedInClass === 0) {
    out.push("_None._", "");
    return out;
  }
  for (const f of findings) out.push(...renderFindingBlock(f));
  if (omittedInClass > 0) {
    out.push(
      `_${omittedInClass} more ${plural(omittedInClass, "finding")} not shown — capped by \`maxFindings\` (see Summary)._`,
      "",
    );
  }
  return out;
}

function renderOptionalSection(
  optional: ReportFinding[],
  includeNiceToHave: boolean,
  hiddenOptional: number,
  omittedOptional = 0,
): string[] {
  const out: string[] = ["## Optional Improvements", ""];
  if (!includeNiceToHave) {
    out.push(
      hiddenOptional > 0
        ? `_${hiddenOptional} optional ${plural(hiddenOptional, "improvement")} hidden. Enable \`review.includeNiceToHave\` to include them._`
        : "_None._",
      "",
    );
    return out;
  }
  if (optional.length === 0 && omittedOptional === 0) {
    out.push("_None._", "");
    return out;
  }
  for (const f of optional) out.push(...renderFindingBlock(f));
  if (omittedOptional > 0) {
    out.push(
      `_${omittedOptional} more ${plural(omittedOptional, "finding")} not shown — capped by \`maxFindings\` (see Summary)._`,
      "",
    );
  }
  return out;
}

function renderFindingBlock(f: ReportFinding): string[] {
  const c = f.cluster;
  const out: string[] = [`### ${sanitizeInline(c.merged_title)}`, ""];

  out.push(`- **Severity:** ${c.severity}`);
  out.push(`- **Category:** ${c.category}`);
  out.push(`- **Confidence:** ${c.confidence.toFixed(2)}`);
  out.push(`- **Human review likelihood:** ${c.human_review_likelihood.toFixed(2)}`);
  out.push(`- **File:** ${c.file === null ? "(none)" : `\`${c.file}\``}`);
  out.push(`- **Lines:** ${renderLines(c)}`);
  out.push(
    `- **Reported by:** ${c.agreement} ${plural(c.agreement, "reviewer")}, ` +
      `${c.source_finding_ids.length} ${plural(c.source_finding_ids.length, "finding")} merged (${c.source_agents.join(", ")})`,
  );
  out.push(`- **Skeptic:** ${skepticNote(f)}`);
  out.push(`- **Score:** ${f.score.toFixed(2)}`);
  out.push("");

  out.push(`**Why this matters:** ${sanitizeInline(c.claim)}`, "");
  out.push(...renderEvidence(c.evidence));
  out.push(...renderSuggestion("Suggested fix", c.suggested_fix));
  out.push(...renderSuggestion("Suggested test", c.suggested_test));
  out.push("");
  return out;
}

/**
 * The skeptic line for one finding. A keep-on-failure fallback (timeout etc.)
 * is stated in the finding itself — not just the JSON artifacts — so a reader
 * always knows when the precision gate sat out (first-demo follow-up).
 */
function skepticNote(f: ReportFinding): string {
  if (f.skeptic?.failure != null) {
    const what = f.skeptic.failure.kind === "timeout" ? "timed out" : `failed (${f.skeptic.failure.kind})`;
    return `⚠ ${what} — finding kept by recall-first fallback (unvalidated)`;
  }
  // `support` can come from the full skeptic record or (when only
  // final_findings.json is available) the joined skeptic_support_level.
  if (f.support !== null) return `support ${f.support}`;
  if (f.skeptic === null) return "not run";
  return f.skeptic.decision.action === "downgrade" ? "deterministic checks passed with warnings" : "deterministic checks passed";
}

function renderLines(c: FindingCluster): string {
  return c.line_start === 0 && c.line_end === 0
    ? "file-level (no line range)"
    : `${c.line_start}-${c.line_end}`;
}

/**
 * Evidence with the strongest items inline and the long tail collapsed. Merged
 * evidence is ordered strongest-first (mergeCluster), so the inline slice is
 * the most representative; everything stays in the JSON artifacts regardless.
 */
function renderEvidence(evidence: string[]): string[] {
  const inline = evidence.slice(0, MAX_INLINE_EVIDENCE);
  const rest = evidence.slice(MAX_INLINE_EVIDENCE);
  const out: string[] = ["**Evidence:**"];
  out.push(...inline.map((e) => `- ${sanitizeInline(e)}`));
  if (rest.length > 0) {
    out.push(
      "",
      `<details><summary>${rest.length} more evidence ${plural(rest.length, "item")}</summary>`,
      "",
      ...rest.map((e) => `- ${sanitizeInline(e)}`),
      "",
      "</details>",
    );
  }
  out.push("");
  return out;
}

/** A nullable suggestion. Multi-line / long ones are fenced inside `<details>`. */
function renderSuggestion(label: string, value: string | null): string[] {
  if (value === null || value.trim() === "") return [];
  const trimmed = value.trim();
  if (trimmed.includes("\n") || trimmed.length > 200) {
    return [`<details><summary>${label}</summary>`, "", fence(trimmed), "", "</details>", ""];
  }
  return [`**${label}:** ${trimmed}`, ""];
}

function renderSuggestedTests(displayed: ReportFinding[]): string[] {
  const tests: string[] = [];
  for (const f of displayed) {
    const t = f.cluster.suggested_test;
    if (t !== null && t.trim() !== "") tests.push(t.trim());
  }
  const out: string[] = ["## Suggested Tests", ""];
  if (tests.length === 0) {
    out.push("_None._", "");
    return out;
  }
  for (const t of tests) {
    out.push(t.includes("\n") ? fence(t) : `- ${sanitizeInline(t)}`);
  }
  out.push("");
  return out;
}

/* ----------------------------- verification ------------------------------ */

function renderVerificationSection(v: PacketVerification, paths: ArtifactPaths): string[] {
  const out: string[] = ["## Verification Results", ""];
  if (!v.ran) {
    out.push("_Verification not run (detection only). Re-run with `--verify` to execute._", "");
    return out;
  }
  out.push(`- **Result:** ${v.allPassed ? "all passed ✓" : "failures present ✗"}`);
  if (v.install) out.push(...renderVerificationCommand(v.install, "Install"));
  for (const cmd of v.commands) out.push(...renderVerificationCommand(cmd));
  out.push("");
  out.push(`_Full output: ${link(paths.reportMd, paths.verification.initial)}_`, "");
  return out;
}

function renderVerificationCommand(c: PacketVerificationCommand, label = ""): string[] {
  const prefix = label ? `${label} ` : "";
  const status = c.passed ? "✓" : c.timedOut ? "timed out ✗" : "✗";
  const lines = [`- ${prefix}\`${c.command}\`: exit ${c.exitCode ?? "—"} ${status}`];
  if (!c.passed) {
    const output = (c.stderrPreview || c.stdoutPreview || c.spawnError || "").trim();
    if (output) lines.push("", "<details><summary>output</summary>", "", fence(output), "", "</details>");
  }
  return lines;
}

/* ------------------------------- dropped --------------------------------- */

function renderDropped(dropped: DroppedEntry[]): string[] {
  const out: string[] = ["## Dropped Findings", ""];
  if (dropped.length === 0) {
    out.push("_None._", "");
    return out;
  }
  out.push(`${dropped.length} ${plural(dropped.length, "finding")} dropped and not shown above:`, "");
  for (const d of dropped) {
    out.push(`- **${sanitizeInline(d.title)}** — ${sanitizeInline(d.reason)} _(${d.stage})_`);
  }
  out.push("");
  return out;
}

/* ------------------------------- artifacts ------------------------------- */

function renderRawArtifacts(input: ReportInput): string[] {
  const { paths, options } = input;
  const out: string[] = ["## Raw Artifacts", ""];
  const targets: string[] = [
    paths.runMetadata,
    paths.context.packetJson,
    paths.context.packetMd,
    paths.normalized.allFindings,
    paths.deduped.clusters,
  ];
  if (options.skepticEnabled) targets.push(paths.skeptic.results);
  if (options.judgeEnabled) targets.push(paths.judge.ranked, paths.finalFindings);
  for (const t of targets) out.push(`- ${link(paths.reportMd, t)}`);
  out.push("");
  return out;
}

/* ------- helpers: link/fence/sanitizeInline/plural in markdownHelpers.ts ------- */
