import { describe, it, expect } from "vitest";
import { renderHtmlReport, HTML_INLINE_EVIDENCE } from "../../src/report/generateHtmlReport.js";
import { esc, safeHttpHref } from "../../src/report/htmlHelpers.js";
import type { ReportInput } from "../../src/report/reportModel.js";
import { getArtifactPaths } from "../../src/storage/artifactPaths.js";
import { makeReviewPacket } from "../fixtures/reviewPacket.js";
import type {
  FinalFinding,
  FindingCluster,
  SkepticResult,
} from "../../src/findings/schema.js";

const paths = getArtifactPaths("/base", "test-run");

function cluster(overrides: Partial<FindingCluster> = {}): FindingCluster {
  return {
    cluster_id: "cluster-001",
    merged_title: "a finding",
    source_finding_ids: ["a-001"],
    source_agents: ["reviewer_a"],
    agreement: 1,
    category: "correctness",
    severity: "medium",
    confidence: 0.6,
    human_review_likelihood: 0.5,
    file: "src/a.ts",
    line_start: 10,
    line_end: 12,
    claim: "a real, actionable claim",
    evidence: ["concrete evidence"],
    suggested_fix: null,
    suggested_test: null,
    needs_code_change: true,
    ...overrides,
  };
}

function finalFinding(overrides: Partial<FinalFinding> = {}): FinalFinding {
  return {
    ...cluster(),
    final_classification: "blocker",
    final_score: 0.88,
    judge_reasoning: "crash path",
    skeptic_support_level: "strong",
    ...overrides,
  };
}

function skepticTimeout(cluster_id = "cluster-001"): SkepticResult {
  return {
    cluster_id,
    source: "fallback",
    checks: {
      hard_failures: [],
      soft_warnings: [],
      signals: { file_in_changeset: true, has_line_anchor: true, line_in_diff: true, line_near_diff: true },
      notes: [],
    },
    model_verdict: null,
    decision: {
      action: "keep",
      reason: "Skeptic could not complete (timeout: timed out after 90000ms); kept pending human review.",
      softened_from_model_action: null,
    },
    failure: { kind: "timeout", message: "timed out after 90000ms" },
    attempts: 2,
  };
}

function makeInput(overrides: Partial<ReportInput> = {}): ReportInput {
  return {
    packet: makeReviewPacket(),
    clusters: [cluster()],
    candidates: [cluster()],
    skepticResults: [],
    ranked: [],
    final: [finalFinding()],
    rawFindingCount: 1,
    meta: { toolVersion: "0.1.0", generatedAt: "2026-01-01T00:00:00.000Z", runId: "test-run" },
    options: { maxFindings: 20, includeNiceToHave: false, judgeEnabled: true, skepticEnabled: true },
    paths,
    ...overrides,
  };
}

describe("htmlHelpers", () => {
  it("esc escapes the full metacharacter set", () => {
    expect(esc(`<a b="c" d='e'>&`)).toBe("&lt;a b=&quot;c&quot; d=&#39;e&#39;&gt;&amp;");
  });

  it("safeHttpHref allows only plain http(s) URLs", () => {
    expect(safeHttpHref("https://github.com/org/repo/pull/1")).toBe(
      "https://github.com/org/repo/pull/1",
    );
    expect(safeHttpHref("javascript:alert(1)")).toBeNull();
    expect(safeHttpHref("data:text/html;base64,PGI+")).toBeNull();
    expect(safeHttpHref("vbscript:evil")).toBeNull();
    expect(safeHttpHref("  javascript:alert(1)")).toBeNull();
    expect(safeHttpHref("//evil.example.com")).toBeNull();
  });
});

describe("renderHtmlReport", () => {
  it("renders the top summary, sections, filter UI, and footer", () => {
    const html = renderHtmlReport(makeInput());
    expect(html).toContain("<!doctype html>");
    expect(html).toContain("AI pre-review verdict");
    expect(html).toContain("Not ready — 1 blocker must be fixed before human review.");
    expect(html).toContain("Raw findings");
    expect(html).toContain("Must fix before human review");
    expect(html).toContain("Should fix before human review");
    expect(html).toContain("Nice to have");
    expect(html).toContain("Verification");
    expect(html).toContain("Dropped findings");
    expect(html).toContain("Raw artifacts");
    expect(html).toContain('id="f-search"');
    expect(html).toContain('id="f-severity"');
    expect(html).toContain('id="f-category"');
    expect(html).toContain('id="f-file"');
    expect(html).toContain('id="f-support"');
    expect(html).toContain("Generated by pr-war-room v0.1.0");
    expect(html).toContain("run test-run");
  });

  it("requires no external network assets", () => {
    const html = renderHtmlReport(makeInput());
    expect(html).not.toMatch(/<script[^>]+src=/i);
    expect(html).not.toMatch(/<link[^>]+href=/i);
    expect(html).not.toMatch(/@import/i);
    expect(html).not.toMatch(/url\(\s*['"]?https?:/i);
    // The PR link is the single allowed external reference.
    const refs = [...html.matchAll(/https?:\/\/[^"'\s<)]+/g)].map((m) => m[0]);
    expect(refs.length).toBeGreaterThan(0);
    expect(refs.every((u) => u.startsWith("https://github.com/org/repo"))).toBe(true);
  });

  it("escapes hostile titles, claims, evidence, and file names everywhere", () => {
    const hostile = finalFinding({
      merged_title: `<script>alert(1)</script>`,
      claim: "claim with ``` fence and <b>markup</b> and \"quotes\"",
      file: `src/<img src=x onerror=alert(2)>.ts`,
      evidence: [`evidence </article><script>alert(3)</script>`],
      suggested_fix: `</details><script>alert(4)</script>`,
      suggested_test: "`backticked` <svg onload=alert(5)>",
    });
    const html = renderHtmlReport(makeInput({ final: [hostile] }));
    expect(html).not.toContain("<script>alert");
    expect(html).not.toContain("<img src=x");
    expect(html).not.toContain("<svg onload");
    expect(html).not.toContain("</article><script>");
    // One <script> only: the static filter script.
    expect([...html.matchAll(/<script/gi)]).toHaveLength(1);
    // The content survives, escaped.
    expect(html).toContain("&lt;script&gt;alert(1)&lt;/script&gt;");
  });

  it("does not link a PR whose html_url is not plain http(s)", () => {
    const packet = makeReviewPacket();
    packet.pr.htmlUrl = "javascript:alert(1)";
    const html = renderHtmlReport(makeInput({ packet }));
    expect(html).not.toMatch(/href\s*=\s*["']?javascript:/i);
  });

  it("shows the strongest evidence inline and collapses the tail", () => {
    const many = Array.from({ length: 10 }, (_, i) => `evidence item ${i + 1}`);
    const html = renderHtmlReport(makeInput({ final: [finalFinding({ evidence: many })] }));
    for (let i = 0; i < HTML_INLINE_EVIDENCE; i++) {
      expect(html).toContain(`evidence item ${i + 1}`);
    }
    expect(html).toContain(`Show ${10 - HTML_INLINE_EVIDENCE} more evidence item`);
  });

  it("marks a skeptic-timeout fallback loudly on the affected card and in the summary", () => {
    const html = renderHtmlReport(
      makeInput({
        skepticResults: [skepticTimeout()],
        final: [finalFinding({ skeptic_support_level: null })],
      }),
    );
    expect(html).toContain("Skeptic timed out");
    expect(html).toContain("recall-first fallback");
    expect(html).toContain("1 kept by recall-first fallback (1 timed out)");
  });

  it("summarizes agreement as reviewers + merged finding count", () => {
    const html = renderHtmlReport(
      makeInput({
        final: [
          finalFinding({
            agreement: 3,
            source_agents: ["a", "b", "c"],
            source_finding_ids: ["a-1", "b-1", "b-2", "c-1"],
          }),
        ],
      }),
    );
    expect(html).toContain("3 reviewers, 4 findings merged");
  });

  it("renders verification command results with collapsible failure output", () => {
    const packet = makeReviewPacket();
    packet.verification = {
      enabled: true,
      ran: true,
      allPassed: false,
      install: null,
      commands: [
        {
          command: "npm test",
          exitCode: 1,
          passed: false,
          timedOut: false,
          spawnError: null,
          stdoutPreview: "",
          stderrPreview: "1 test failed <script>bad()</script>",
        },
      ],
    };
    const html = renderHtmlReport(makeInput({ packet }));
    expect(html).toContain("✗ Failures present");
    expect(html).toContain("npm test");
    expect(html).not.toContain("<script>bad()");
    expect(html).toContain("&lt;script&gt;bad()&lt;/script&gt;");
  });

  it("lists dropped findings with stage and reason", () => {
    const dropped = cluster({ cluster_id: "cluster-002", merged_title: "speculative style nit" });
    const html = renderHtmlReport(
      makeInput({
        clusters: [cluster(), dropped],
        ranked: [
          {
            cluster_id: "cluster-002",
            source: "llm",
            model_verdict: { final_classification: "drop", model_score: 0.1, reasoning_summary: "stylistic" },
            decision: {
              classification: "drop",
              score: 0.1,
              include_in_main_report: false,
              reason: "purely stylistic",
              softened_from_model_classification: null,
            },
            failure: null,
            attempts: 1,
          },
        ],
      }),
    );
    expect(html).toContain("speculative style nit");
    expect(html).toContain("purely stylistic");
    expect(html).toContain("Show 1 dropped finding");
  });

  it("is deterministic for identical input", () => {
    const input = makeInput();
    expect(renderHtmlReport(input)).toBe(renderHtmlReport(makeInput()));
  });
});
