import { describe, it, expect } from "vitest";
import { renderFixReport, type FixReportInput } from "../../src/report/generateFixReport.js";
import type { FixFindingOutcome } from "../../src/fix/schema.js";
import { getArtifactPaths } from "../../src/storage/artifactPaths.js";
import type { VerificationResults } from "../../src/workspace/schema.js";
import { makeFinalFinding } from "../fixtures/finalFinding.js";

const paths = getArtifactPaths("/base");

function makeOutcome(overrides: Partial<FixFindingOutcome> = {}): FixFindingOutcome {
  return {
    cluster_id: "cluster-001",
    title: "off-by-one in range check",
    file: "src/a.ts",
    classification: "should_fix_before_review",
    final_score: 0.8,
    status: "fixed",
    summary: "clamped the loop bound",
    needs_manual_review: null,
    edits_applied: 1,
    failure: null,
    ...overrides,
  };
}

function makeVerification(overrides: Partial<VerificationResults> = {}): VerificationResults {
  return {
    schemaVersion: 1,
    enabled: true,
    enabledSource: "flag",
    ran: true,
    skipReason: null,
    detectedCommands: ["npm test"],
    configuredCommands: [],
    installCommand: null,
    executedCommands: ["npm test"],
    skippedCommands: [],
    install: null,
    results: [
      {
        command: "npm test",
        exitCode: 0,
        passed: true,
        durationMs: 100,
        timedOut: false,
        spawnError: null,
        stdoutPreview: "",
        stderrPreview: "",
        stdoutBytes: 0,
        stderrBytes: 0,
        logFile: null,
      },
    ],
    allPassed: true,
    startedAt: "2026-01-01T00:00:00.000Z",
    finishedAt: "2026-01-01T00:00:10.000Z",
    ...overrides,
  };
}

function makeInput(overrides: Partial<FixReportInput> = {}): FixReportInput {
  return {
    pr: { owner: "org", repo: "repo", number: 123 },
    totalFinalFindings: 4,
    fixableCount: 1,
    maxFindings: 5,
    selected: [makeFinalFinding()],
    outcomes: [makeOutcome()],
    patchWritten: true,
    workspaceLeftPatched: false,
    verification: makeVerification(),
    headMoved: false,
    meta: { toolVersion: "0.1.0", generatedAt: "2026-01-01T00:00:00.000Z" },
    paths,
    ...overrides,
  };
}

describe("renderFixReport", () => {
  it("only links fix_verification.json when the verification artifact was written", () => {
    // The zero-selected early return never writes it — a dead link reads as a bug.
    const without = renderFixReport(makeInput({ verification: null }));
    expect(without).not.toContain("(fix_verification.json)");
    const withVerification = renderFixReport(makeInput());
    expect(withVerification).toContain("(fix_verification.json)");
  });

  it("renders the summary, fixed section, apply instructions, and footer", () => {
    const md = renderFixReport(makeInput());
    expect(md).toContain("# AI Fix Report");
    expect(md).toContain("[org/repo#123](https://github.com/org/repo/pull/123)");
    expect(md).toContain("1 of 1 fixable finding attempted");
    expect(md).toContain("1 fixed, 0 failed, 0 skipped");
    expect(md).toContain("## Fixed");
    expect(md).toContain("**What changed:** clamped the loop bound");
    expect(md).toContain("git apply .ai-review/patch.diff");
    expect(md).toContain("reverted to the PR head");
    expect(md).toContain("_Generated by pr-war-room v0.1.0");
    expect(md.endsWith("\n")).toBe(true);
  });

  it("notes the maxFindings cap when more findings were fixable than attempted", () => {
    const md = renderFixReport(
      makeInput({ fixableCount: 9, maxFindings: 1, outcomes: [makeOutcome()] }),
    );
    expect(md).toContain("1 of 9 fixable findings attempted (capped at `fix.maxFindings=1`)");
  });

  it("renders failures with their kind and the reviewer-suggested fix fallback", () => {
    const md = renderFixReport(
      makeInput({
        selected: [makeFinalFinding({ suggested_fix: "use `i < n` instead" })],
        outcomes: [
          makeOutcome({
            status: "failed",
            summary: null,
            edits_applied: 0,
            failure: { kind: "search_not_found", message: "search string not found in src/a.ts" },
          }),
        ],
      }),
    );
    expect(md).toContain("## Not Fixed");
    expect(md).toContain("`search_not_found`");
    expect(md).toContain("Reviewer-suggested fix");
    expect(md).toContain("use `i < n` instead");
  });

  it("surfaces needs_manual_review notes as blockquotes", () => {
    const md = renderFixReport(
      makeInput({ outcomes: [makeOutcome({ needs_manual_review: "add a regression test" })] }),
    );
    expect(md).toContain("> **Needs manual review:** add a regression test");
  });

  it("sanitizes markdown-hostile titles and messages", () => {
    const md = renderFixReport(
      makeInput({
        outcomes: [makeOutcome({ title: "evil `code` [link](x) *bold*\nnewline" })],
      }),
    );
    expect(md).toContain("evil \\`code\\` \\[link\\](x) \\*bold\\* newline");
  });

  it("explains a skipped verification and how to enable it", () => {
    const md = renderFixReport(
      makeInput({
        verification: makeVerification({
          ran: false,
          skipReason: "verification disabled (pass --verify or set verification.enabled=true)",
          executedCommands: [],
          results: [],
        }),
      }),
    );
    expect(md).toContain("_Verification skipped — verification disabled");
  });

  it("renders failed verification commands with their output", () => {
    const md = renderFixReport(
      makeInput({
        verification: makeVerification({
          allPassed: false,
          results: [
            {
              command: "npm test",
              exitCode: 1,
              passed: false,
              durationMs: 100,
              timedOut: false,
              spawnError: null,
              stdoutPreview: "",
              stderrPreview: "2 tests failed",
              stdoutBytes: 0,
              stderrBytes: 14,
              logFile: null,
            },
          ],
        }),
      }),
    );
    expect(md).toContain("failures present ✗");
    expect(md).toContain("`npm test`: exit 1 ✗");
    expect(md).toContain("2 tests failed");
  });

  it("describes the --apply workspace state and omits dead patch links when none written", () => {
    const appliedMd = renderFixReport(makeInput({ workspaceLeftPatched: true }));
    expect(appliedMd).toContain("left PATCHED (`--apply`)");
    expect(appliedMd).toContain("already contains these");

    const noPatchMd = renderFixReport(
      makeInput({ patchWritten: false, outcomes: [makeOutcome({ status: "failed", failure: { kind: "timeout", message: "t" } })] }),
    );
    expect(noPatchMd).toContain("none produced");
    expect(noPatchMd).toContain("_No patch was produced, so there is nothing to apply._");
    expect(noPatchMd).not.toContain("[patch.diff]");
  });

  it("warns when the PR head moved since the review", () => {
    const md = renderFixReport(makeInput({ headMoved: true }));
    expect(md).toContain("the PR head moved since the review run");
  });
});
